### ISSUE TITLE
UnsupportedDataExtension error on trying to get json data from Google Spreadsheet via GAS

### ISSUE THREAD

**Issue by ikedhidenori** [stevenosloan/middleman-data_source#3]
I tried to get json data from Google Spreadsheet via Google Apps Script, but failed.

what I did is:

 1.publishd spreadsheet data (here's data: [spreadsheet data](https://docs.google.com/spreadsheets/d/1nlrukb7TZme3iUsJCG2lLJDsmYtFSbbYOxa0UZu50xo/pubhtml
))

![](http://i.gyazo.com/eac7fbbf81d2aa61955907ab6568d52a.png)

2.wrote Google Apps Script code and publishd (here's [sciprt](#code) and [execution result](https://script.google.com/macros/s/AKfycbyzNbrKRfz5c-4ya4-ScyIyUqr4GKUeDXFda6-CFlQ9x13yRxP-/exec), success.  )
ref. [Google Apps Script で spreadsheet のデータを JSON として読み込む / Getting spreadsheet data as json format via Google Apps Script ](http://daichan4649.hatenablog.jp/entry/2014/02/08/160453)

```
[{"id":1,"name":"apple"},{"id":2,"name":"beer"},{"id":3,"name":"cookie"}]
```

3.middleman server up, and encounterd `UnsupportedDataExtension` error like below.

``` middleman
/Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-data_source-0.5.0/lib/middleman/data_source/extension.rb:71:in `decode_data': Middleman::DataSource::Extension::UnsupportedDataExtension (Middleman::DataSource::Extension::UnsupportedDataExtension)
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-data_source-0.5.0/lib/middleman/data_source/extension.rb:36:in `block (2 levels) in initialize'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/data.rb:149:in `call'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/data.rb:149:in `data_for_path'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/data.rb:163:in `method_missing'
        from /Users/hi/Sites/lavida.co.jp/v2/dev/config.rb:88:in `initialize'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/extensions.rb:162:in `instance_eval'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/extensions.rb:162:in `initialize'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/data.rb:33:in `initialize'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/application.rb:204:in `initialize'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:56:in `new'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:56:in `inst'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/preview_server.rb:107:in `new_app'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/preview_server.rb:24:in `start'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/cli/server.rb:81:in `server'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in `method_missing'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
        from /Users/hi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
        from /Users/hi/.rbenv/versions/2.1.2/bin/middleman:23:in `load'
        from /Users/hi/.rbenv/versions/2.1.2/bin/middleman:23:in `<main>'
        from /Users/hi/.rbenv/versions/2.1.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/hi/.rbenv/versions/2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

here's my setting on `config.rb`

```config.rb
activate :data_source do |c|
  c.files = {
    "https://script.google.com/macros/s/AKfycbyzNbrKRfz5c-4ya4-ScyIyUqr4GKUeDXFda6-CFlQ9x13yRxP-/exec)" => "Sheet1"
  }
end
```

I'm so excited becourse middleman can handle data from other API data, but it failed...

By the wáy, I tried the JSON data on local json file (that is, copy and paste the JSON data to local file), then I found suceed without any errors. so the json data is right.

anyone has ideas?

thanks.

<a name="code"></a>
Code for converting spreadsheet data to JSON (Google Apps Script)
``` GAS
var URL_BOOK = 'https://docs.google.com/spreadsheet/ccc?key=1nlrukb7TZme3iUsJCG2lLJDsmYtFSbbYOxa0UZu50xo';
var SHEET_NAME = 'Sheet1';
 
function doGet(e) {
  var url = URL_BOOK;
  var sheetName = SHEET_NAME;
 
  var book = SpreadsheetApp.openByUrl(url);
  var sheet = book.getSheetByName(sheetName);
 
  // {hoge : 'fuga'};
  var json = convertSheet2JsonText(sheet);
  return ContentService.createTextOutput(JSON.stringify(json)).setMimeType(ContentService.MimeType.JSON);
}
 
function convertSheet2JsonText(sheet) {
  // first line(title)
  var colStartIndex = 1;
  var rowNum = 1;
  var firstRange = sheet.getRange(1, 1, 1, sheet.getLastColumn());
  var firstRowValues = firstRange.getValues();
  var titleColumns = firstRowValues[0];
 
  // after the second line(data)
  var lastRow = sheet.getLastRow();
  var rowValues = [];
  for(var rowIndex=2; rowIndex<=lastRow; rowIndex++) {
    var colStartIndex = 1;
    var rowNum = 1;
    var range = sheet.getRange(rowIndex, colStartIndex, rowNum, sheet.getLastColumn());
    var values = range.getValues();
    rowValues.push(values[0]);
  }
 
  // create json
  var jsonArray = [];
  for(var i=0; i<rowValues.length; i++) {
    var line = rowValues[i];
    var json = new Object();
    for(var j=0; j<titleColumns.length; j++) {
      json[titleColumns[j]] = line[j];
    }
    jsonArray.push(json);
  }
  return jsonArray;
}
```

**Comment by stevenosloan** [comment]
This comes up because I was *really* lazy w/ the data type detection (https://github.com/stevenosloan/middleman-data_source/blob/master/lib/middleman/data_source/extension.rb#L65-L73), and your endpoint doesn't end with `.json`.

I think it'd be good to add a feature for specifying the content-type and/or giving a proc for doing your own decoding instead of just depending on the extension.

**Comment by stevenosloan** [comment]
Hey @ikedhidenori took me a little bit but I believe I came to a good solution for this (some nice added features :+1: )

Could you try out on this feature branch:
```ruby
# Gemfile
gem 'middleman-data_source', git: 'git@github.com:stevenosloan/middleman-data_source.git',
                             branch: 'feat/set_types_and_define_decoders'
```

Then to pull the data:
```ruby
# config.rb
activate :data_source do |c|

  c.sources = [
    {
      alias: "Sheet1",
      path:  "https://script.google.com/macros/s/AKfycbyzNbrKRfz5c-4ya4-ScyIyUqr4GKUeDXFda6-CFlQ9x13yRxP-/exec",
      type:  :json
    }
  ]

end
```

If you could let me know if the new docs in the readme make sense as well that'd be great https://github.com/stevenosloan/middleman-data_source/tree/feat/set_types_and_define_decoders#custom-data-types

thanks!

**Comment by ikedhidenori** [comment]
Surprising!  That's exactly what I want!
It works and seems perfect for me.
Thanks, steven!

**Comment by stevenosloan** [comment]
Awesome, glad that works for you. I think it's a nice added feature set.

I'll get a new version cut & pushed later today. Thanks!

**Comment by stevenosloan** [comment]
Ok, [`0.6.0`](https://rubygems.org/gems/middleman-data_source/versions/0.6.0) is out so you can use that instead of the branch now.
